<html>
<head>
    <meta charset="utf-8">
    <title> Aplikacja </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"/>
    <style>

    </style>
</head>
<body>

<form name="myForm" action=""  method="post">
    Liczba: <input type="text" name="number">
    <input type="submit" value="Potwierdź"></form>

</body>
<#include "footer.ftlh">
</html>
